version: '3.4'

services:

  catalogdb:
    image: mongo

  catalogapiapp:
    image: ${DOCKER_REGISTRY-}catalogapiapp
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPIApp/Dockerfile
volumes:
  mongo_data:
 