version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  
  orderdb:
    container_name: orderdb
    environment:
       SA_PASSWORD: "mahfuzShazol12345611111111"
       ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin 
      - POSTGRES_PASSWORD=admin1234 
      - POSTGRES_DB=DiscountDb

  pgdmin:
    container_name: pgdmin
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgdmin_data:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com 
      - PGADMIN_DEFAULT_PASSWORD=admin1234

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data 
    

  catalogapiapp:
    container_name: catalogapiapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basketapiapp:
    container_name: basketapiapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discountgrpc"
    depends_on: 
      - basketdb
    ports:
      - "8001:80"


  discountapiapp:
    container_name: discountapiapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on: 
      - discountdb
    ports:
      - "8002:80"


  discountgrpc:
    container_name: discountgrpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on: 
      - discountdb
    ports:
      - "8003:80"


  orderingapiapp:
    container_name: orderingapiapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=mahfuzShazol12345611111111"
    depends_on: 
      - orderdb
    ports:
      - "8004:80"

