version: '3.4'

services:

  catalogdb:
    image: mongo

  basketdb:
   image: redis:alpine
 
  discountdb:
   image: postgres
  
  orderdb:
   image:  mcr.microsoft.com/mssql/server:2017-latest

  pgdmin:   
   image: dpage/pgadmin4

  portainer:
   image: portainer/portainer-ce

  catalogapiapp:
    image: ${DOCKER_REGISTRY-}catalogapiapp
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPIApp/Dockerfile
  basketapiapp:
    image: ${DOCKER_REGISTRY-}basketapiapp
    build:
      context: .
      dockerfile: Services/Basket/BasketAPIApp/Dockerfile

  discountapiapp:
    image: ${DOCKER_REGISTRY-}discountapiapp
    build:
      context: .
      dockerfile: Discount/DiscountAPIApp/Dockerfile

  discountgrpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Discount/DiscountGrpc/Dockerfile

  orderingapiapp:
    image: ${DOCKER_REGISTRY-}orderingapiapp
    build:
      context: .
      dockerfile: Services/Ordering/Ordering/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgdmin_data:
 



